<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Zend_Oauth_Exception" namespace="" name="Zend_Oauth_Exception" abstract="false" final="false" start="33" end="33">
  <file path="/var/www/_modules/social_integration/trunk/docs/en/phpdox/../../../thirdparty/Zend/Oauth" file="Exception.php" realpath="/var/www/_modules/social_integration/trunk/thirdparty/Zend/Oauth/Exception.php" size="1081" time="2015-03-14T10:23:59+13:00" unixtime="1426281839" sha1="589eb795aec3b06475623f0c68814f8243a5bbbb" relative="thirdparty/Zend/Oauth/Exception.php"/>
  <docblock>
    <description/>
    <category value="Zend"/>
    <package value="Zend_Oauth"/>
    <copyright value="Copyright (c) 2005-2011 Zend Technologies USA Inc. (http://www.zend.com)"/>
    <license name="http://framework.zend.com/license/new-bsd     New BSD License"/>
  </docblock>
  <extends full="Zend_Exception" namespace="" name="Zend_Exception"/>
</class>
